### ISSUE TITLE
Не удается установить библиотеку

### ISSUE THREAD

**Issue by Shamil-R** [kebrick/pyiikoapi#2]
Здравствуйте! 
Пытаюсь установить библиотеку командой 
`pip3 install pyiikoapi==0.0.1 `
и получаю ошибку
![image_2021-04-18_14-24-26](https://user-images.githubusercontent.com/8791201/115144092-58f34600-a053-11eb-9817-4074384ac4b4.png)
Такая же ошибка при попытки установки библиотеки из файла requirements.txt  в контейнере.

Помогите, пожалуйста, решить эту проблему.

**Comment by kebrick** [comment]
Проблема была в моих кривых руках, я вроде бы исправил свою проблему поэтому попробуйте установить

**Comment by Shamil-R** [comment]
Подтверждаю - работает!
Спасибо за быстрый ответ!
