### ISSUE TITLE
Ошибка при создании/обновлении клиента

### ISSUE THREAD

**Issue by Shamil-R** [kebrick/pyiikoapi#3]
При попытке создать клиента
`
api = CardService(credential.user_id, credential.user_secret, credential.organisation_id)
res = api.create_or_update({
                "customer": {
                    "phone": "88005553535"
                }
            })
`
возникает ошибка
`{'exception': 'InvalidOperationException', 'message': "The incoming message has an unexpected message format 'Raw'. The expected message formats for the operation are 'Xml'; 'Json'. This can be because a WebContentTypeMapper has not been configured on the binding. See the documentation of WebContentTypeMapper for more details."}
`
Подскажите, пожалуйста, как решить эту проблему?

**Comment by kebrick** [comment]
Попробуйте обновить сервис
pip install -U pyiikoapi
И попробуйте снова. Отпишитесь если всё получится)
Спасибо
